# -*- coding: utf-8 -*-
"""Actividad 2 POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekLKx_yRR_93ZqZh5Cg2IAU5i38tX0KT

Parte 1

Capitulo 3: Estructura secuencial (18, 19, 21)

Ejercicio Propuesto: 18
"""

codigo=int(input("Código empleado:"))
nombres=input("Nombres:")
horas_mes=int(input("Horas de trabajo (mes):"))
valor_hora=int(input("Valor por hora de trabajo:"))
porcentaje_retencion=float(input("Porcentaje de retencion: "))

retencion= (horas_mes*valor_hora) * (porcentaje_retencion/100)

salario_bruto= horas_mes*valor_hora
salario_neto= int(salario_bruto - retencion)

print(f"Código: {codigo}")
print(f"Nombres: {nombres}")
print(f"Salario bruto: {salario_bruto}")
print(f"Salario neto: {salario_neto}")

"""Ejercicio Propuesto: 19"""

Lado=float(input("Valor lado triangulo"))

perimetro = Lado * 3
altura = (3**0.5 /2)*Lado
area = (3**0.5 /4) * Lado**2

print(f"El périmetro del triangulo es: {perimetro}, el valor de la altura: {altura:.2f} y el area del triangulo {area:.2f}")

"""Ejercicio Propuesto: 21"""

Lado_1=float(input("Valor lado 1 triangulo: "))
Lado_2=float(input("Valor lado 2 triangulo: "))
Lado_3=float(input("Valor lado 3 triangulo: "))

perimetro= Lado_1+Lado_2+Lado_3
semiperimetro= perimetro/2
s=semiperimetro
area= (s*(s - Lado_1)*(s - Lado_2)*(s - Lado_3))**0.5

print("Perimetro: ", perimetro)
print("Semiperimetro: ", semiperimetro)
print(f"Area: {area:.2f}")

"""Capitulo 4: Estructura decisión lógica (Er: 7, 10, 11, 12, 13, 14, 15)(Ep: 22, 23, 24)

Ejercicios Resueltos

Ejercicio resuelto: 7
"""

A=float(input("Ingrese A: "))
B=float(input("Ingrese B: "))

if A>B:
  valor= "mayor"

elif A<B:
  valor= "menor"

else:
  valor= "igual"

print(f"A es {valor} que B")

"""Ejercicio Resuelto: 10"""

numero_inscripcion= int(input("Ingrese el numero de inscripcion: "))
nombres= input("Ingrese los nombres: ")
patrimonio= int(input("Ingrese su patrimonio: "))
estrato= int(input("Ingrese su estrato: "))

cobro_base= 50000
adicion=0

if patrimonio > 2000000 and estrato > 3:
  adicion= patrimonio * 0.03

cobro_final= cobro_base + adicion

print("Numero de inscripcion: ", numero_inscripcion)
print("Nombres: ", nombres)
print("Pago por matricula: ", cobro_final)

"""Ejercicio Resuelto: 11"""

numeros=[]

for i in range(1,4):
  n=int(input(f"ingrese el numero {i}: "))
  numeros.append(n)

mayor= max(numeros)

print("El mayor es: ", mayor)

"""Ejercicio Resuelto: 12"""

nombre= input("Nombre: ")
horas= int(input("Horas trabajo: "))
valor= int(input("Valor por hora: "))

x=horas

if horas > 40:
  x= x-40
  if x > 8:
    x= x-8
    pago= 40*valor + 8*(2*valor) + x*(3*valor)

  else:
    pago= 40*valor + x*(2*valor)

else:
  pago= horas*valor

print(f"El pago semanal sera de {pago} COP")

"""Ejercicio Resuelto: 13"""

compra= float(input("Valor compra: "))
color= input("Color bolita: ")
color= color.lower()

descuento=0

if color == "verde":
  descuento = 0.1*compra

elif color == "amarilla":
  descuento = 0.25*compra

elif color == "azul":
  descuento = 0.5*compra

elif color == "roja":
  descuento = 1*compra

elif color == "blanca":
  descuento = 0*compra

precio_final= compra-descuento

print(f"Dado que saco una bolita {color}, su compra valda {int(precio_final)} COP")

"""Ejercicio Resuelto: 14"""

departamento_1= float(input("Ventas departamento 1: "))
departamento_2= float(input("Ventas departamento 2: "))
departamento_3= float(input("Ventas departamento 3: "))

salario= float(input("Salario vendedores: "))

salario_d1= salario
salario_d2= salario
salario_d3= salario

ventas= departamento_1 + departamento_2 +  departamento_3

tercio= ventas*0.33

if departamento_1 > tercio:
  salario_d1= salario + (salario*0.2)

if departamento_2 > tercio:
  salario_d2= salario + (salario*0.2)

if departamento_3 > tercio:
  salario_d3= salario + (salario*0.2)

salarios=[salario_d1, salario_d2, salario_d3]

for i in range(0,3):
  x= i+1
  print(f"El salario del departamento {x} sera de {int(salarios[i])} COP")

"""Ejercicio Resuelto: 15"""

A=float(input("Peso bola A: "))
B=float(input("Peso bola B: "))
C=float(input("Peso bola C: "))
D=float(input("Peso bola D: "))

bolas=[A, B, C, D]
iguales=[]
diferente=[]3

for i in range(len(bolas)):
  bola=bolas[i]

  for j in range(0,4):
    if bola == bolas[j] and i != j:
      iguales.append(bola)

  if bola not in iguales:
    diferente.append(bola)

if diferente[0] < iguales[0]:
  comparacion= "menor"

elif diferente[0] > iguales[0]:
  comparacion= "mayor"

if diferente[0]==A:
  print(f"A es la esfera diferente y tiene un peso {comparacion} a las otras")

if diferente[0]==B:
  print(f"B es la esfera diferente y tiene un peso {comparacion} a las otras")

if diferente[0]==C:
  print(f"C es la esfera diferente y tiene un peso {comparacion} a las otras")

if diferente[0]==D:
  print(f"D es la esfera diferente y tiene un peso {comparacion} a las otras")

"""Ejercicios Propuestos

Ejercicio Propuesto: 22
"""

