# -*- coding: utf-8 -*-
"""Ejercicio resuelto: 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWAI3IkwbI11VPKQ2uygSEKIH9m8VFqL
"""

A=float(input("Ingrese A: "))
B=float(input("Ingrese B: "))

if A>B:
  valor= "mayor"

elif A<B:
  valor= "menor"

else:
  valor= "igual"

print(f"A es {valor} que B")