# -*- coding: utf-8 -*-
"""Ejercicio propuesto: 22

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWAI3IkwbI11VPKQ2uygSEKIH9m8VFqL
"""

nombre=input("Ingrese el nombre del trabajador: ")
salario=float(input("Ingrese el salario por hora trabajada: "))
horas=int(input("Ingrese las horas trabajadas en el mes: "))

salario_final= salario * horas

print(f"Trabajador: {nombre}")

if salario_final > 450000:
  print(f"Salario mensual: {int(salario_final)} COP")