# -*- coding: utf-8 -*-
"""Ejercicio resuelto: 11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWAI3IkwbI11VPKQ2uygSEKIH9m8VFqL
"""

numeros=[]

for i in range(1,4):
  n=int(input(f"ingrese el numero {i}: "))
  numeros.append(n)

mayor= max(numeros)

print("El mayor es: ", mayor)